language: node_js
node_js:
  - "0.10"
  - "0.12"
sudo: false
install:
  - npm install
script:
  - npm test

notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/5b9a0a2586cae3f46ac7"
    on_success: change
    on_failure: always
    on_start: false
